export const FETCH_HOMEDATA = 'FETCH_HOMEDATA';
export const HOME_API_CALL_SUCCESS = "HOME_API_CALL_SUCCESS";
export const HOME_API_CALL_FAILURE = "HOME_API_CALL_FAILURE";

export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const PROJECTS_API_CALL_SUCCESS = "PROJECTS_API_CALL_SUCCESS";
export const PROJECTS_API_CALL_FAILURE = "PROJECTS_API_CALL_FAILURE";

export const FETCH_EXPERIENCE ='FETCH_EXPERIENCE';
export const EXPERIENCE_API_CALL_SUCCESS = "EXPERIENCE_API_CALL_SUCCESS";
export const EXPERIENCE_API_CALL_FAILURE = "EXPERIENCE_API_CALL_FAILURE";